version: "3"
services:
  plex:
    build:
      context: plex/
      args:
        VERSION: "1.5.3.3580-4b377d295"
    container_name: plex
    network_mode: "host"
    restart: unless-stopped
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /var/lib/plexmediaserver:/config
      - /mnt/storage/Media:/data
  plexpy:
    image: jkaberg/docker-plexpy
    container_name: plexpy
    restart: unless-stopped
    volumes:
      - /var/lib/plexpy:/var/lib/plexpy
    ports:
      - "8282:8181"
  sickbeard:
    image: timhaak/sickbeard
    container_name: sickbeard
    user: "1000"
    volumes:
      - /etc/sickbeard:/config
      - /mnt/storage:/data
    ports:
      - "8081:8081"
    restart: unless-stopped
  sync:
    image: bittorrent/sync
    container_name: sync
    user: "1000"
    restart: unless-stopped
    volumes:
      - /var/lib/btsync:/mnt/sync
      - /home/jonathan/btsync:/mnt/mounted_folders/storage
    ports:
      - "8888:8888"
      - "55555"
  flexget:
    image: pfragoso/docker-flexget
    container_name: flexget
    user: "1000"
    volumes:
      - ~/.flexget/:/home/flexget/.flexget
    restart: unless-stopped
  transmission:
    image: dperson/transmission
    container_name: transmission
    environment:
      - TRPASSWD=$TRANSMISSION_PASS
      - USERID=1000
    volumes:
      - /mnt/storage/Torrents:/var/lib/transmission-daemon/downloads
      - /mnt/storage/Incomplete:/var/lib/transmission-daemon/incomplete
      - /etc/transmission-daemon:/var/lib/transmission-daemon/info
    ports:
    - 0.0.0.0:12345:12345/tcp
    - 0.0.0.0:12345:12345/udp
